### ISSUE TITLE
Request: Ships only piloted by the Crew.

### ISSUE THREAD

**Issue by DrakeEldridge** [msummers123/Movecraft-3#107]
So, I am not sure if something has been done already, but is there away to stop ships being stolen/driven by non-crew members.

I was thinking something like:
Crews. Captain/maker of the "Ship" sign (The sign that has
 Line 1: CraftType

Line 2: Optional

Line 3: Optional

Line 4: Optional) 

can make a crew by doing something like /crew create (name of crew) and inviting players to join his crew by doing /crew invite (playername) etc etc (players able to accept or reject with similar commands)

and the plugin makes a group.yml or something with list of crews and people in the crew. So like 

Crews:
 - Team01
     -  Playerblah
     -  Playerboo
 - Team02
     -  Playerguy
     -  Playerbob

etc etc

then on the "Ship" sign have the crew name on it. Like
 Line 1: CraftType

Line 2: Optional

Line 3: Optional

Line 4: Crew Name eg: Team01

That means only members in Team01 can use the ship signs to drive the ship. (All the driving signs etc would need to be like the main sign, only crew members can drive it. The main "Ship" sign tells those signs who is the crew that owns them.)

Im not sure if this would work, its just an idea.

But with that others cant use "Ship" signs unless a crew member. But then there is the problem of, what if the non-crew member places a new "Ship" sign on the ship and steals it. If it was impossible to place 2 "Ship" signs on the same ship, awesome, problem solved.

But is that cant be done, how about:
Well if its possible, perhaps "Ship" signs can only be created if there isnt already a ship sign in a certain radius (configured in the config yml)
That means "Ship" signs cant be made in the proximity of another "Ship" sign and so there cant bee 2 on the same ship.  This wouldnt effect signs already created, so ships can sail close to each other without anything happening. But means ships cant be made really close to other ships.

Because I have world Guard, players cant break blocks/ships except in certain regions. So this should make ships thief-proof and be a cool crew system. (With the crew sign for setting crew spawn, this plugin would be perfect for pirate ship servers. Crews able to respawn/spawn on ships, and ships can only be driven by crew members.

Just some idea for this plugin to make ships no vulnerable to thieves and crew only signs.
Thanks for reading

Drake

**Comment by mwkaicz** [comment]
I thought about this in past:

Plugin can't make craft detection per each sign placing... it's complicated process and can takes a large amount of CPU when structure looks like big craft but isn't. F.e: Creating sign-based shop will make a houndred wasted detections.

About WorldGuard: I'm working on WGCustomFlags and Towny support for Movecraft, so hold on, you will have more options :)

**Comment by DrakeEldridge** [comment]
I was going to use world guard to keep players from building/breaking blocks in towns / docks and able to break blocks etc at sea. so ships should be safe if docked. But theft is still main issue. plugin would be perfect if there was a way to stop other crews/non-crew members from stealing someones ship. What about permission nodes. if captain makes the crew. in the crew.yml or something it goes
Crews:
    - crew name
       -  crew permissions
                - movecraft.sign.crewname (e.g billys)
      - crew members
               - name of crew member
               - name of crew member
               - name of crew member

etc

and the main "ship sign" has permissions and only those with the perm                 - movecraft.sign.crewname (e.g billys) can use it. Like Server Signs plugin.  One SVS you can do permission based signs. So only players with the right perm can use that sign.


I dont know. Im not a plugin maker, so I have no idea how hard it is. But anti theft, as well as some kind of Crew System, would be really cool.

**Comment by mwkaicz** [comment]
At this time, best way is dock a ship in private are and then you have two options:
- remove all signs (when players haven't perms for commands)
- join the ship to something what is docked in flightless blocks.

Your file doesn't prevent anything, because isn't locked to any craft,and i think this isn't good way because craft can be changed with any else plugin.


I was thinking more about it today
better will be something like this:

sign something like this:
```Crew Members:```
```John```
```Frank```
```Jack```

for the case, when Crew has more then 3 players (example for 5 members):
```Crew Members:```
```John```
```Frank```
```lists: 3```

```Crew Members:```
```Jack```
```Tylor```
```lists: 3```

```Crew Members:```
```Anne_Bonny```
``````
```lists: 3```

So ... why counts of lists? Here is answer:
(provided that craft isn't in protected area)
When new sign is placed and at First row is ```Crew Members:```
plugin will do DetectionTask, when It will be completed, look to the list of block and check if there is any sign with ```Crew Members:``` 
- when there isn't it allows to create 
- when it is, it allows place this sign only when all signs has written same count of lists and when count of existing signs is lower than this count, everithing else is denied. 

(Here can be also rule that only member, which is actually on the list can create new part of list, but I don't see reason for this now, maybe someone else?)

BUT! There is a Question if prevent these signs from explosions and manual destroying (except crew) ... i think that this could be optional.  Because Ship must be still protected from destroying blocks which holds these crew lists.

I belive that this can solve problem of stealing ships forever.

**Comment by DrakeEldridge** [comment]
sounds good to me. I cant use this plugin for my server until i have some way of stopping theft. (Making a One Piece Pirate  server) SO having some way of solving it is really good. As for signs being destoyed. players wouldnt be able to break the signs in a non-building/breaking region, like docks and towns. But in the ocean/ blocks breakable area, I think its fine for ships to be fought over, and destroyed. So signs breaking in the ocean would be fine. 
Atm 

    remove all signs (when players haven't perms for commands)
    join the ship to something what is docked in flightless blocks.

is not really that useful. Would require someone with perms to break the signs or placing non-moveable blocks at the docks, so players wouldnt be able to dock without staff online. 

Anyway. Any means of making it impossible to steal ships would be good. Really hope this problem can be solved.

**Comment by mwkaicz** [comment]
In private area, this isn't problem, In public protected area it problem is. But can be solved, We have something like private lever from sign ... It can be locked only by person who created it. I thought to remake it for something like more universal. Sign which can be switched by anyone, but unlocked only by person who locked it.

**Comment by DrakeEldridge** [comment]
wud be cool if tht leaver or sign could be done on the ship signs. so the captain or crew members can lock the ship sign, and only the person who locked it can unlock it.

**Comment by msummers123** [comment]
Yeah, there are a lot of ways to do this. Here is how we do it:

Extended piston head (id:34) is a forbidden block on the ship - you shouldn't have pistons extended while moving anyway due to a minecraft limitation. Pistons are fine, just not being extended while moving.

Somewhere on the interior of the ship is a lever next to a piston. Flip the switch, and the ship is "locked". It can not be piloted as long as the piston is extended.

Every city has a large "protected airspace" area around the city. Inside that area explosions are not allowed, fire doesn't spread, and you can't destroy blocks that are typically used in airship walls (wool, doors, hardened clay, glass, etc)

The door on the airship is protected using Lockette. 

So with this system:
 - In a public protected area, only the person on the lockette sign can enter the ship and unlock it
 - You can't steal the ship by "towing" since if you attach your ship to the victim ship, you are locked down too
 - In the unprotected wilds someone can kill the crew, enter your ship by blowing a hole in a wall, loot any chests (we don't allow lockette protection on chests, only doors and trapdoors), and steal your ship

So if you park in a public protected area, you will be fine, but piracy outside the protected areas is still viable.

**Comment by DrakeEldridge** [comment]
thts cool. I dont use lockette though. Personally dont like it. But could try. Add the whole crew to the lockette sign so crew can unlock and lock, others cant. 

if there are other ways of doing this without other plugins would be nice. Better to have crew system, and anti theft built into movecraft without needing to use outside plugins which could end up conflicting in the future or something. but this might work.

**Comment by msummers123** [comment]
Implemented (sort of). Actual syntax is a Pilot sign, where the second, third, and fourth lines contain users authorized to pilot that craft.

**Comment by DrakeEldridge** [comment]
Thanks so much. Good to know :D quick question, does that mean only 3 people can ever pilot the ship cause of the lines on the sign? Or can more be added with second pilot sign?

**Comment by Pocketkid2** [comment]
You would have to add a second pilot sign

**Comment by msummers123** [comment]
Actually, Drake was correct you can only ever have 3. The way the engine works is that every pilot sign found on the craft must contain the name of the pilot that is attempting to pilot the craft. Otherwise I could steal your ship by taking a craft that already has a pilot sign with my name on it, parking next to your craft, then re piloting it after merging with your craft.

**Comment by DrakeEldridge** [comment]
I see. Is there a way to make like, an inheritence thing? So instead of names, you have line 2, 3 or 4 say "Blue team" and only those added to the blue team crew can pilot it, which is inherited from a group list in a crew config or something? So names are added to crew config, and the pilot sign takes the crew names from that?

 I mean, I love that you added this feature, I am def going to keep using movecraft. Just wondering if that was ever a possibility to have a crew list config or something that the pilot sign looks at?
