### ISSUE TITLE
I teleport when ship moves.

### ISSUE THREAD

**Issue by Lekingmoonya** [msummers123/Movecraft-3#137]
Me and my friend where playing on my server and when he piloted the ship, i got teleported back wards and I have trouble moving because I'm teleporting.

Windows 8.1
i5-3337u
1GB Server
Spigot 1.8
Only movecraft
2~4 people on server

Pls help

**Comment by msummers123** [comment]
Wait... when he piloted it (not moved it), you started teleporting? That be the most bizarre thing I have ever heard.

I must have misunderstood. Could you go step by step in what you are doing, and what you are seeing?

**Comment by Lekingmoonya** [comment]
Ok sorry if that was confusing. My friend took control of an airship and then started moving it. (Right clicking the stick) At that time, I was on the bridge but I wanted to go to the back of the ship. But when he moved the ship while I was walking, I teleported to my initial position. (The bridge) If that's confusing I'll record it next time.

From Leki

**Comment by mwkaicz** [comment]
That's standart situation. If you want walking on the board during ship translation. Your ship must use Cruise option. Promlem is that translation is async and when translation starts you you are still on same block, because theoreticaly move of the craft can occure 20x per second.

**Comment by Lekingmoonya** [comment]
But when I use the cruise option it gets really blocky. (Not smoth)

**Comment by mwkaicz** [comment]
yes, it should be, because cruise function is for bigger jumps, so in normal state you have f.e: 
```
canCruise: false
speed: 3.0
```
that means you can move a ship 3x per second. If you want equivalent speed with cruising your craft file must contains f.e. this:
```
canCruise: true
speed: 0.5
cruiseSkipBlocks: 6
```

Both ships have same speed, each needs 2 seconds for move over 6 blocks.
But in first ship server must update map 6x  and you have only 1/3 second for move on the board.
Second ship needs only one map update and you have 2 seconds for moving on the board before ship makes next step.
But what's important: you should not to use *canCruise: true* when you have speed bigger than 1.0 ... that's not reason why was this function created.

**Comment by mwkaicz** [comment]
@msummers123: What about to add optional cruisSpeed to .craft file?
When it's set cruising can get it instead of normal speed and we can keep speed for normal moves.
Then will not be necessary to have two craft types for cruising and normal moving.

**Comment by Lekingmoonya** [comment]
This is what I'm experiencing -->
https://www.youtube.com/watch?v=1-C3exhrMhM&feature=youtu.be

**Comment by msummers123** [comment]
What you have shown there would be typical for a relatively high latency connection to the server, or a fairly slow server. It's normally not that bad for a ship that small, but that would be normal for, say, a 10k ship on my own server.

I am planning some small improvements, but overall this is just an unavoidable consequence of the underlying Minecraft engine. The best advice I can give you is not to move around while your ship is cruising.

The fact is we just can't move thousands of blocks at a time and guarantee the player will always be standing on the blocks they are supposed to be as the ship is reconstructed around them. Because your Minecraft client gets all of the updates from the server in an unpredictable order.
