### ISSUE TITLE
[Server Owner]Unable to locate sign 

### ISSUE THREAD

**Issue by wisewhyforge** [msummers123/Movecraft-3#180]
On movecraft every time I try to move my airship it spams an error:

[21:35:17 ERROR]: Block at -190,81,-310 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@7faa4b8d.
 Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[21:35:17 ERROR]: Block at -199,81,-302 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@4c4d0f81.
 Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[21:35:17 ERROR]: Block at -192,81,-302 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@cdf7258.
Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[21:35:17 ERROR]: Block at -201,81,-310 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@669e9979.
 Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[21:35:17 ERROR]: Block at -178,81,-302 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@4b455004.
 Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[21:35:17 ERROR]: Block at -171,81,-302 is SIGN_POST but has net.minecraft.server.v1_8_R3.TileEntityComparator@6f507fea.
 Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

This happens on and on when my ship tries to move, causing major lag. What does it mean that "Bukkit will attempt to fix it"? It sometimes will not show the error, but sometimes it has an error.

P.S. I won't be able to respond that quickly because it is nighttime at 9:45 PM and I need to go to bed.

Thanks,
wisewhyforge

**Comment by wisewhyforge** [comment]
B U M P

**Comment by mwkaicz** [comment]
If you want quick solution, try to remove signal comparators from your ship.

If you want something else, you must wait for next release probably. But at this moment I'm not sure, if this was solved correctly before (@msummers123 knows more about this than me).  Movecraft uses signs for transporting few complicated blocks from one location to another, I think that your problem caueses some version change, but definitely: Bukkit can't fix it, because source of this bug is Movecraft and his wrong replacing block from comparator to the sign.

**Comment by wisewhyforge** [comment]
Ok, but you need comparators and It only happens on big ships.

**Comment by mwkaicz** [comment]
interesting, how big is a big ship? :)

**Comment by msummers123** [comment]
This is a known bug in Spigot as well as CraftBukkit servers. I have submitted a bug report ages ago, but no avail yet. I found a workaround to prevent chunk corruption, however I can not prevent it logging the warning. It's annoying, because on my server I have literally gigabytes of these warning messages. Although, other than that, it is harmless. I'm sorry I don't have a better answer.

**Comment by msummers123** [comment]
Oh, but more info: the bug itself deals with how Spigot / Bukkit removes comparators. It does not clean up the metadata correctly. It would happen with any plugin that removes a comparator block, and places a new block with metadata. But Movecraft just tends to move a whole lot of them. For example, WorldEdit occasionally spits this out.

**Comment by wisewhyforge** [comment]
I have a question. What is the NPC Airship used for? How can I use it?

**Comment by msummers123** [comment]
It is used by admins on the Airship Pirates World server when they are running NPC events. I'm going to go ahead and close this ticket.
