### ISSUE TITLE
How to add /contacts

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#184]
I am looking for information on how to properly add the block multiplier function for / contacts. And if someone is willing to help, are there permission nodes for this?

**Comment by pistols12** [comment]
Bump?

**Comment by msummers123** [comment]
There is currently no permissions node for the /contacts command, if you want to disable it simply don't specify a "detectionMultiplier" or a "underwaterDetectionMultiplier" setting. To add detection, add a line similar to the following to your .craft file:
detectionMultiplier: 10.0
and/or:
underwaterDetectionMultiplier: 1.0

The higher the number, the greater the distance the craft can be detected at. Also, the larger the craft, the greater the distance it can be detected at. Detection distance increases at the square root of the size so that, for example, increasing the size of a craft by 4 times increases it's detection range by double.

**Comment by pistols12** [comment]
Thank you, I just didn't know the formula for detection and had 0 interest in attempting to find out via trial and error. 

CASE CLOSED.
