### ISSUE TITLE
Harvest blade takes damage, or needs to be repaired.

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#186]
I have a suggestion for Harvest blade crafts. Say if you have a plow, or a Ram, or a drill.. And you never ever have to stop to repair it, you could use this thing to get infinite resources basically, I am wondering if it's possible to add a simple damage slash Health to the Harvest blade. So that depending on how many blocks you harvest, you take x amount of damage. Every once in awhile this would force you to stop and repair your your blade Ram or drill bit.

**Comment by mwkaicz** [comment]
Correct me if I'm wrong, I'm not using repairs, but i think that you need missing blocks for repair, or not? so how you can get infitive resource?

About blade health: It is possible, BUT: there is easy way how to glitch it. We haven't any option how save these values after pilot release the craft. Because from that point it isn't craft, but only couple of blocks. So repair damaged blades will be pretty fast /release + /pilot.

**Comment by pistols12** [comment]
Ah ok, makes sense. Well thanks for the insight, that's what I was looking to know.
