### ISSUE TITLE
Can't add blocks to 'allowedBlocks'

### ISSUE THREAD

**Issue by adhoc92** [msummers123/Movecraft-3#193]
I added "- 42" to the list so I could use iron blocks on my Airskiff, but once added, I couldn't take control of my ship. When I went back and deleted "- 42", everything worked perfectly again. None of the other blocks I added worked either. Any ideas?

**Comment by mwkaicz** [comment]
Hi, your problem will be in wrong YAML format. (all *.craft files are YAML)
Try compare your craft file, with examples on https://en.wikipedia.org/wiki/YAML


The most frequent mistakes are wrong count of spaces in lists or wrong usage of quotation marks.

It should be something like this:
`allowedBlocks:`
`____- 42`
(replace underscore with spaces, ... I replaced spaces with underscore in example above, because github removes spaces on the start of the line)

there must be two or four spaces before dash (standart is two, Movecraft uses four, but it doesn't matter, important is that there must be two at least) ... when you haven't spaces there Yaml parser can't recognize that the item is part of array/list

**Comment by pistols12** [comment]
The best way that I have found is to use an online YAML parser. You
basically can copy the bad file as is and paste it into the online YAML
parser and find the error, it tells you the exact lines parsing issues are
on. From there, paste another copy of the bad file into a notepad plus plus
to fix and then find the issues via the online parser, fix the file in
notepad and update the online parser everytime you fix a pasring issue,
once it finally is debugged and the Online paser has output, paste it back
into the previously bad craft file, TA-DA!

with this with this method I have fixed over 100 issues in 20 mins or so..
they were all in one single file, they were peppered in between nearly 1000
lines of code.  the above response is good for a few issues, but without
the online parser  I would have never been able to figure out that many
issues with in one single file.

**Comment by pistols12** [comment]
http://yaml-online-parser.appspot.com/

**Comment by mwkaicz** [comment]
@pistols12 best way is write it correctly at first :)

**Comment by pistols12** [comment]
Hahahahah, touche!

**Comment by pistols12** [comment]
I definitely scolded the heck outta the guy with 1,000 lines of code in a
yaml whom never thought to check it as he went... LoL...then it was too
much for them when it came time to fixing. Like... COME ON!!

**Comment by adhoc92** [comment]
Thanks guys. I'm away from home for another day or 2, but when I get back I'll give it another shot.

**Comment by msummers123** [comment]
I believe this is taken care of
