### ISSUE TITLE
TNT messed up

### ISSUE THREAD

**Issue by keough99** [msummers123/Movecraft-3#194]
when tnt cannons on my server are fired they blow up and the tnt duplicates it self but shows the cobwebs and stuff and the only plugin i have that alters tnt is movecraft

**Comment by pistols12** [comment]
I believe you're having a timing issue with your cannons, as TNT properties are not affected by movecraft-. The cobwebs are just tracers

**Comment by pistols12** [comment]
Please correct me if I'm wrong guys

**Comment by keough99** [comment]
its not the timing ive checked it and ive checked tnt mechanic changes in 1.9 and there are not any changes to tnt in 1.9 i think its a bug becuase movecraft also has the contact explosives

**Comment by pistols12** [comment]
Well if you really think it's movecraft- I would suggest verifying by
uninstalling the plug-in briefly. Like backing up your plug-in settings,
removing them, double-checking, and then going from there.

**Comment by mwkaicz** [comment]
as I know pistols12 is right, only access to the tnt is generating tracers from flying tnt. Try to remove Movecraft temporary and validate function of your tnt cannon

**Comment by mwkaicz** [comment]
just remove Movecraft*.jar file temporarily

**Comment by pistols12** [comment]
The server that I frequent does not use TNT cannons as much, but as a lot of others do and no one else's had this issue, it's highly unlikely to me that movecraft- is the cause. Unless it was recently updated, but then again more people would be having this issue and more tickets would show up with the same problem

**Comment by mwkaicz** [comment]
I strongly recommend to use Cannons plugin instead of TNT cannons ... there is no risk from unexpected explosions, no need to have water in allowedBlocks etc.

**Comment by keough99** [comment]
i did a test i think movecraft was part of the problem but it might also be a issue with 1.9 spigot

**Comment by mwkaicz** [comment]
So cannon not expoloded without Movecraft.jar?

**Comment by pistols12** [comment]
I'm a huge fan of the Cannons plugin as well, I know a lot of people are not. But to me it just takes a lot of the painstaking work out of it so any player can make a working ship, and they are aimable, have 3 stages to loading, can be hooked to redstone for automation, cause concussions with no helm, burn you when hot,so on and so fourth making them more realistic than TNT cannons.

**Comment by keough99** [comment]
one did but i think its a spigot 1.9 issue thats part of it but movecraft could also be a small part of it
i have cannons but it can be buggy and its impossible to make a good design with it

**Comment by pistols12** [comment]
Nothing is impossible, Outlook is everything.

**Comment by pistols12** [comment]
I have plenty of good working cannons on my server.

We are on 1.9 then also use TNT cannons as well, with no fault. So not really sure what to say at this point, as it seems like it's a setup or operator issue

**Comment by keough99** [comment]
its hard to actually make a good design and its not very customizable like tnt cannons

**Comment by pistols12** [comment]
On the contrary, they are times more customizable in my opinion.

You can choose and even make ammo (6 types of cannon ammo comes stock, from using cobble, to tnt, to diamond, grape shot, to rockets)

You can choose how high up you can aim, as well as left and right, Tumi fixed TNT cannons always bug me cause you could never really am left or right. You couldn't diagonally shoot. And you didn't know where you were actually shooting. With TNT cannons that actually gives you a marker of where your aim to hit. As well as the ability stock to aim left 45 degrees and right 45 degrees. Much more customizable and much easier than TNT cannons in terms of aiming and ammo. Much more realistic too... even down to the soot that accumulates in the barrel per shot is configurable, you can set the limit at which you have to clean the barrel from the soot accumulation.

You can set the Heat that accumulates on the cannon Barrel per shot as well, so that you literally have to cool the cannon before firing it again with water or other items that cool the cannon down. If you don't you get burned by the hot Cannon Barrel.

You also literally have to use a ramrod to pack the shots, gunpowder as well, and if you use too much gun powder the Canon has a chance to explode.

And I also mention that you can configure the concussion level, so that if you don't wear a helmet when firing cannons you will literally be dazed and blinded because of a concussion. To me there is not really anything more customizable on the TNT cannons as opposed to the Cannons plugin.

**Comment by keough99** [comment]
I might have figured out the issue with tnt tnt is no longer directionally based even though it was implemented in 1.8.7 spigot might not have implemented it until 1.9 which it's causing cannon designs to be broken

**Comment by msummers123** [comment]
Yeah, there are very strong opinions on the subject of using redstone cannons vs the plugin. I can see advantages and disadvantages to both. But I will continue to develop the plugin in such a way that both server types can use it.
