### ISSUE TITLE
Error in console regarding crafts:

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#239]
09.12 17:10:04 [Server] ERROR Block at 2,053,138,5,122 is SIGN_POST but has net.minecraft.server.v1_9_R1.TileEntityComparator@89db670. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover. 09.12 17:10:05 [Server] ERROR Block at 2,053,138,5,128 is SIGN_POST but has net.minecraft.server.v1_9_R1.TileEntityComparator@151ce85e. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

**Comment by pistols12** [comment]
What the heck is going on here??

**Comment by keough99** [comment]
It's normal for crafts, I have it all the time mostly on fighters because a sign will turn into red stone or a comparator as a visual glitch but it gets corrected by the server it just gives an error message, this happens on crafts that are fast that it will output this warning but it's nothing to worry about
