### ISSUE TITLE
[BUG] Craft getting stuck on air

### ISSUE THREAD

**Issue by 1000000000** [msummers123/Movecraft-3#77]
A SubAirship (craft file modified so it does not need fuel and can be made of prismarine) is stuck on a block of air. I was attempting to pilot it out of an underground hangar into the ocean. To aid movement around the hangar the craft has two stone half slabs on the bottom which slot into grooves in the floor of the hangar. Note that to exit the hangar the craft moves horizontally into a wall of water instead of down.

No errors were generated on the console either at start up or when the craft became stuck.

Movecraft Version: 3.1.X62

Spigot Version: git-Spigot-59b08be-c051558 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

![The craft cannot move because its path is obstructed! @ -264,33,-1416](https://cloud.githubusercontent.com/assets/842338/5733187/0b39eae6-9b6d-11e4-89c1-63c86c49291a.png)The craft cannot move because its path is obstructed! @ -264,33,-1416

![Showing block -264,33,-1416](https://cloud.githubusercontent.com/assets/842338/5733206/4d4f27fc-9b6d-11e4-82b5-9994df5a3ba3.png)Showing block -264,33,-1416 (the block is the air block above the stone block I am looking at)

--Thanks in advance

**Comment by msummers123** [comment]
Could you get me a schematic that includes both the craft and the area its trying to get through? The problem probably has to do with how the engine is forming the craft due to its geometry, and how it adds in air that it believes is inside the crafts borders so it doesn't fill with water. 

So the exact shape of the craft is important, because that's what it uses to figure out what air blocks should be added.

**Comment by 1000000000** [comment]
Absolutely, here is the schematic: https://dl.dropboxusercontent.com/u/30765884/StuckSubAirship.schematic

If it is too small I can make a larger one.

**Comment by 1000000000** [comment]
Sorry for not mentioning it earlier but if it helps, I am also running WorldEdit and CraftBook on this server. The sponge blocks present in the schematic were put there to keep the water from spilling into the hangar (CraftBook feature).

**Comment by TylerS1066** [comment]
I've had glitchy results with small horizontal tunnels into/out of water, once it sunk my ship (recolored Minnow mk2)
My suggestion is to try and either make the tunnel bigger or have the water to air transition be vertical

**Comment by msummers123** [comment]
Sorry for the delay, it took a while to find the free time to look at this. Yeah, moving horizontally from a dry area to a water area is just going to cause problems. It cannot accurately tell the water level from the surrounding terrain, which is has to do in order to tell if it should put water behind the ship or not, and to move the air in the interior with the craft.

What it is actually doing in this example is adding the air blocks under the body to the hull because it mistakenly believes they are part of the interior. Then when it tries to move those air blocks, they collide with the stone.

But even if you fix that, you are going to be putting air blocks in the ocean on the outside of the cave, or water on the inside of it. And it will get worse every time the ship moves through the area. Eventually you will have a massive air bubble on the bottom of your ocean. 

I'm afraid the engine just doesn't do this well, and I don't see an easy way for it to figure out that the blocks on the inside of the cave should be replaced with air when it moves out, and the blocks on the outside of the cave should be replaced with water.
