### ISSUE TITLE
2 new signs: Lookout Report and Ship Status (Bosun Report?)

### ISSUE THREAD

**Issue by msummers123** [msummers123/Movecraft-3#81]
Lookout report would tell you of any other ships, their pilot, type, and size. The radius it could detect ships at should be dynamic. I favor something like this:

Always exactly 200 blocks:
LookoutReportRadius: 200

Depends on ship size:
LookoutReportRadius: [size*0.01]

Ship Status would tell you what percentage of your original ship remains, what percentage of your flyblocks remains, and how much fuel you have left

**Comment by danielcbailey** [comment]
I like both the ideas. In fact, for ship status, there could be a command to define a location near an important part of the ship (like engine room 1 or cannon 3) and if it could find a block within 3 blocks of the command (or other radius) it would run successfully and could be stored in a similar fashion as the repair sign. If those blocks are suddenly missing, the plugin could show on the sign: Cannon 3 silenced and there could be a way to dismiss the message to get the next or to return to normal function of the sign. That way could be right clicking the sign. I think it is important to get the heading for a lookout report sign because it is important for tactical reasons and the look outs could tell you. Lastly, I think there could be another dismiss feature to know of multiple ships, this could be like asking them what else or next. Plus it would be cool if they reduced the range by half when raining.
-Danielcbailey

**Comment by TylerS1066** [comment]
Seems like Movecraft is removing the need for a crew, I like it because it's hard to get a crew to pilot a ship, everyone wants to pilot their own or a fighter.

**Comment by keough99** [comment]
why dont we have a sign for the /contacts thing it would make it fun + we can assign people to the radar duty so you can have crew and such
