### ISSUE TITLE
MoveCraft crash with ships sinking

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#82]
http://pastebin.com/xfZ87Kt9

**Comment by msummers123** [comment]
Yes, this is the infamous storage crate problem manifesting in an exciting new way...

I would encourage you to have your players empty any storage crates they care about, then disable storage crates in Movecraft's config.yml

Storage crates are very buggy, but since you can use chests there is no real reason to have them. I suggest getting rid of them. They are a legacy feature that I won't be working on.

**Comment by msummers123** [comment]
Let me know if you had any further questions, I would like to close this issue

**Comment by Pocketkid2** [comment]
I dont ever use crates. I have disabled the crates in my config. Could you just remove them from the plugin completely?

**Comment by msummers123** [comment]
Sadly there are people that still use them. They like that they are a container which is an exception to most container control mechanisms. IE: they can have a region where you can't use chests but can still use crates. 

I would love to ditch them for good.
