### ISSUE TITLE
Seperate permissions for commands

### ISSUE THREAD

**Issue by FrozenBeard** [msummers123/Movecraft-3#89]
Via http://dev.bukkit.org/bukkit-plugins/movecraft/?page=2#c2721

Commands should each have their own seperate permissions, I would like to have /release for everyone but not /cruise & /pilot, /Pilot makes it much easier to steal ships for people that forget to lock them down in some-way, and Cruise can be overpowered depending on the ship type setup.
If they are seperated it means players could gain extra commands when they rank up! 

Thanks for the time :)

**Comment by mwkaicz** [comment]
Good idea, I think best way is add something like this perm:
- movecraft.*.release

**Comment by msummers123** [comment]
Just to keep you up to date, this is on the list of things to include

**Comment by msummers123** [comment]
Implemented in latest version. Will be released soon, probably this weekend.
movecraft.commands still exists, for backwards compatibility. But the other commands have been added below it.

For example, if you have type /release, you need either movecraft.commands OR movecraft.commands.release

**Comment by mwkaicz** [comment]
I think that should be good talk and think about commands much more.

few topics: 
- I would like to add commands ascend and descend, but there is confict with WE.
- command for reload craft types should be also helpful
- there is lot of commands but not any main command which gather them into one group ... i know that ```/movecraft pilot something``` is too long, but some optional shortcut instead of ```/movecraft``` in config can solve it.

**Comment by msummers123** [comment]
Implemented in latest version

**Comment by FrozenBeard** [comment]
Awesome.
