### ISSUE TITLE
Crash when right clicking Airship sign

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#92]
http://pastebin.com/aCJtQKpJ

**Comment by msummers123** [comment]
This time it looks like there was a problem with the craft detection detecting blocks in the world, where the world could not provide the blocks the detection task asked for. 

A common cause is overflowing the world boundaries, or the detection task flowing into unloaded chunks. Sometimes people do this by, for example, adding water to the allowedblocks and trying to pilot a craft in the sea. In essence, you are telling Movecraft you want to pilot the entire ocean. 

Another side note on this, is that if you got this error you probably have your block limit on the craft set too high. Because otherwise it would have told you that there were too many blocks before it gave this error. If you keep your block limit reasonable, your life will be better and you will have fewer problems.

**Comment by msummers123** [comment]
I would like to close this, do you have any questions about it?
