### ISSUE TITLE
Large craft sinking causes low TPS

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#96]
On my 1.8 spigot server, I use this plugin. I've got 4G of ram dedicated, and it's not all being used. When a really large craft sinks on the server, i've been noticing that during the sink, the TPS starts to drop. Sometimes this gets as low as 10 TPS. So far it seems that reloading the plugin in some way helps it, but why does that happen?

**Comment by mwkaicz** [comment]
What do you mean realy large?
I'm not sure but I think that this is problem of CPU mainly. Try to  watch CPU usage while a craft is sinking.

**Comment by msummers123** [comment]
Yeah, give a block count. It's probably just that sinking large ships is intensive. On my server, sinking a 19k ship drops the tps to 10. It gets back to the core problem of large crafts. It's not too bad if they just cruise forward, which can be heavily optimized. But if they move diagonally, sink, or worse yet, rotate, the whole server just crawls.

Reloading stops the sinking process, so that would be why that seems to fix it.

There used to be a bug with sinking sometimes causing extraordinary lag. But that was fixed several versions ago. So make sure you are running the most recent version.

**Comment by Pocketkid2** [comment]
Thanks!
